version: "3.1"
services:
  db:
    image: influxdb:1.2.4
    command: -config /etc/influxdb/influxdb.conf
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - influxdata:/var/lib/influxdb
  api:
    image: thierno9/iot-api:v3
    build: ./nodejs
    command: npm start
    ports:
      - 1337:1337
volumes:
  influxdata:
